version: '3.7'
services:
  app-monolitica: #app-monolitica
    container_name: app-monolitica
    image: cesarmoralesh/asesorias-monolitica:1
    build: 
      context: .
    ports:
      - "5000:5000"
    networks:
      - asesorias-red 
networks: 
  asesorias-red: